name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas (arreglado el formato cron)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          screen_name: leticiamontilla
          target_branch: trophy-output
          # Aquí puedes añadir estilos si quieres, pero por ahora déjalo así
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
